language: ruby

services:
  - postgresql

before_script:
  - psql -c 'create database slack_uberzeit_test;' -U postgres

cache:
  bundler: true

rvm:
  - 2.3.4
  - 2.4.0
  - 2.4.2
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
